services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: amavida-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/Belem
      - TZ=America/Belem
    volumes:
      - amavida_n8n_data:/home/node/.n8n

volumes:
  amavida_n8n_data:
